### ISSUE TITLE
Session TTL is not used as shown in example configuration

### ISSUE THREAD

**Issue by cjzness** [aequasi/cache-bundle#36]
The example configuration shows that the session TTL value is set as shown:

```
aequasi_cache:
    session:
        enabled: true
        instance: default
        prefix: "session_"
        ttl: 1800
```

However, the TTL value specified here is not used, instead the `cookie_lifetime` value is used from the Symfony framework session configuration.
